### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by mahmoudhossam** [kennethreitz/python-guide#150]
I was surprised to see there's nothing on JSON here, considering the existence of several good json libraries out there for python.

For example: I want to know why I should use simplejson vs the json module that ships with python.

**Comment by royka** [comment]
an improvement to my original PR that got merged

**Comment by ssundarraj** [comment]
So is this closed?

**Comment by royka** [comment]
I believe it should be however that doesn't stop you from doing a PR to improve the section :)
