### ISSUE TITLE
Confused with one sentence in win.rst

### ISSUE THREAD

**Issue by zhangyangyu** [kennethreitz/python-guide#320]
I am confused with one sentence _You do not need to install or configure anything else to use Python_. in win.rst, in the paragraph right before the title _Setuptools + Pip_. I have seen this sentence in osx.rst and linux.rst and I think it is suitable there. But it seems not suitable in win.rst because you do need to install Python and then maybe do some configuration.

And the first sentence in the _virtualenv_ section is wrong. It should be _After Setuptools & Pip_, not _After Distribute & Pip_.

**Comment by varunagrawal** [comment]
It seems this has been fixed. Can we close this issue?

**Comment by sigmavirus24** [comment]
@varunagrawal what makes you think this has been fixed?

**Comment by varunagrawal** [comment]
I can't seem to find the line on _Distribute & Pip_ in the virtualenv section in win.rst. Also, on reading the section referenced in the first part of the issue, it makes sense.
Your thoughts @sigmavirus24 ?

**Comment by userlerueda** [comment]
@zhangyangyu can you point us to the link were the sentence is mentioned?

**Comment by zhangyangyu** [comment]
I opened this in 2013 and now it's 2017, so I assume it doesn't make sense any more so I close it. :-)
