### ISSUE TITLE
No section on logging?

### ISSUE THREAD

**Issue by lexual** [kennethreitz/python-guide#336]
Is the guide missing a section on logging?

**Comment by tanyaschlusser** [comment]
I would like to give this section a shot, but don't know the best place to put a new section.

Does it belong as its own section in Writing Great Code, maybe after the [documentation page](http://docs.python-guide.org/en/latest/writing/documentation/)? Or maybe as a subsection in the documentation page, or as its own scenario in the Scenario Guide?

Thank you for guidance!
