### ISSUE TITLE
Citation needed for "significant changes" and "hidden bugs" for Apple's built-in Python

### ISSUE THREAD

**Issue by glyph** [kennethreitz/python-guide#359]
The [“Installing Python on Mac OS X”](http://docs.python-guide.org/en/latest/starting/install/osx/) section of this guide claims that Apple's Python contains:

> significant changes that can cause hidden bugs

There's a [pretty complete list of changes](http://opensource.apple.com/source/python/python-60.4/2.7/fix/) on Apple's website, none of which look particularly “significant” to me.  Granted, things like [this](http://opensource.apple.com/source/python/python-60.4/2.7/fix/install.py.ed) maybe cause a little confusion from time to time, but I've personally developed using the system Python for years and years and it's never really caused any significant issues for me.  Plus, re-building things like PyObjC from source is a non-trivial amount of time for users who might want to use Python for automation applications like Scripting Bridge.

Personally when helping novices get their machines set up for learn-python workshops, a “brew install”ed or otherwise source-built Python has occasionally been the source of a lot of confusion for me.  So I’d like it if resources like this guide would stop suggesting it, but I don’t even really know what I could suggest that would assuage your concerns, since the concerns are not even documented.

**Comment by sigmavirus24** [comment]
Closed by #388
