### ISSUE TITLE
Add Chameleon to templating section

### ISSUE THREAD

**Issue by webmaven** [kennethreitz/python-guide#382]
Besides Jinja2, the following should be added as alternate templating solutions.

- [X] Chameleon
- [ ] Mako

**Comment by ssundarraj** [comment]
Is this closed?

**Comment by webmaven** [comment]
I never did a PR for Mako, so no reason for the PR to be closed.

**Comment by gregimba** [comment]
Mako is now in the docs
http://docs.python-guide.org/en/latest/scenarios/web/#templating
