### ISSUE TITLE
add "virtualenvwrapper how to" to "Installing Python on Linux"

### ISSUE THREAD

**Issue by levivm** [kennethreitz/python-guide#469]
I think, it would be nice to add  a short description about how to use virtualenvwrapper , after installing virtualenv.  Specifically in the section: http://docs.python-guide.org/en/latest/starting/install/linux/#installing-python-on-linux

**Comment by toanant** [comment]
I think this issue is already fixed in this commit - [e9eb5da](https://github.com/helenst/python-guide/commit/e9eb5da170e30dbe92819080d1abba681b7538ef). It should be closed now.
