### ISSUE TITLE
question about string concatenation

### ISSUE THREAD

**Issue by codetender** [kennethreitz/python-guide#472]
Hi, guys, very appreciated for your work. Just a little question about string concatenation mentioned in [structure is key](http://docs.python-guide.org/en/latest/writing/structure/#structure-is-key)

> One final thing to mention about strings is that using join() is not always best. In the instances where you are creating a new string from a pre-determined number of strings, using the addition operator is actually faster, but in cases like above or in cases where you are adding to an existing string, using join() should be your preferred method.

```python
foo = 'foo'
bar = 'bar'

foobar = foo + bar  # This is good
foo += 'ooo'  # This is bad, instead you should do:
foo = ''.join([foo, 'ooo'])
```

I don't get the reason that  `foo = ''.join([foo, 'ooo'])` is preferred over `foo += 'ooo'`, regarding only two string are operated, so I do a little benchmark test according to the suggestion above. 

```python 
import timeit

def a():
    foo = 'foo'
    bar = 'bar'
    foobar = foo + bar

def b():
    foo = 'foo'
    foo += 'ooo'

def c():
    foo = 'foo'
    foo = ''.join([foo, 'ooo'])


for i in ['a', 'b', 'c']:
    print i, ":", timeit.timeit("%s()" % i, setup="from __main__ import %s" % i)
```
result:

```
a : 0.220181941986
b : 0.226699829102
c : 0.425080060959
```

I wonder whether the suggestion given in the guide is not based on performance issue or I've done the benchmark test wrong

**Comment by geoelectric** [comment]
I don't think the benchmark is wrong. In fact, I show join as being grossly slower than +=.

mbp:~ geo$ python --version
Python 2.7.9

mbp:~ geo$ python -m timeit 's = "spam"' 's = "".join([s, "spam"])'
1000000 loops, best of 3: 0.233 usec per loop

mbp:~ geo$ python -m timeit 's = "spam"' 's += "spam"'
10000000 loops, best of 3: 0.0688 usec per loop

mbp:~ geo$ python -m timeit 's = "spam"' 's = s + "spam"'
10000000 loops, best of 3: 0.0699 usec per loop

Being idiomatic is a good reason to go the other way, but I must admit that I find the s = s + "foo" version the clearest. At risk of being controversial, clarity is probably a more pythonic value than idiom here.

**Comment by sigmavirus24** [comment]
> I wonder whether the suggestion given in the guide is not based on performance issue

It's based on performance of concatenating a large number of strings at once and it's the recommended practice of the core developers in that case.

**Comment by geoelectric** [comment]
Well, I see you've closed this, but I think this makes at least a couple of people who don't understand the suggestion in the given context. I think you should reconsider the validity of the issue based on that, particularly since newbies are going to be the target audience.

I think you're right, regarding it being more a concern for large strings and/or large numbers of strings. Would you be open to a PR with a change in the text and/or example to make that clearer? 

Right now, it very much reads like a one-off concatenation should always be done with join, specifically for performance reasons. I think that's what's catching people out.

**Comment by sigmavirus24** [comment]
Pull requests are always welcome.
