### ISSUE TITLE
Include peewee in database section?

### ISSUE THREAD

**Issue by coleifer** [kennethreitz/python-guide#499]
Hi Kenneth,

I'd love it if you would consider including [peewee ORM](http://docs.peewee-orm.com) under the [databases](http://docs.python-guide.org/en/latest/scenarios/db/) scenario of your guide. Peewee has a growing, but very devoted, user-base and receives almost 40K downloads a month from PyPI. Peewee is thoroughly documented, has a mailing list, IRC channel, and I am very proactive in responding to questions, GitHub tickets, and other inquiries. It's my hope that given these characteristics, it would be worth including in your guide.

What do you think? If this sounds good to you, I will open a pull-request with my proposed addition.

Thanks,

Charlie

**Comment by syndbg** [comment]
Good to close the issue! :shipit:

**Comment by coleifer** [comment]
Yep, looks like #500 took care of it. Thanks all.
