### ISSUE TITLE
Maybe the pdf isn't newest because can't build the pdf.

### ISSUE THREAD

**Issue by mtunique** [kennethreitz/python-guide#514]
Readthedocs.org can't build the pdf.
There are the [history](https://readthedocs.org/builds/python-guide/) and [log](https://readthedocs.org/builds/python-guide/2264839/).

**Comment by sigmavirus24** [comment]
I don't have access to the RTD project so this will be up to @kennethreitz to fix if he desires to fix it.

**Comment by brittag** [comment]
I don't know what this problem might have been, but the [current PDF](https://media.readthedocs.org/pdf/python-guide/latest/python-guide.pdf) seems to be recently generated and the [builds seem to be passing now](https://readthedocs.org/projects/python-guide/builds/). :)

**Comment by sigmavirus24** [comment]
Thanks @brittag for taking a look at this.
