### ISSUE TITLE
IPython

### ISSUE THREAD

**Issue by jack-yang** [kennethreitz/python-guide#523]
Would http://ipython.org/ worthy of inclusion? This interactive shell is much better IMHO.

**Comment by sigmavirus24** [comment]
Not only do we have IPython, we have it twice.

- http://docs.python-guide.org/en/latest/scenarios/scientific/#ipython
- http://docs.python-guide.org/en/latest/dev/env/#ipython

Is this sufficient?

**Comment by jack-yang** [comment]
My bad. Thanks!

**Comment by sigmavirus24** [comment]
Feel free to send other suggestions @jack-yang 

If you want to check them first, you can search using GitHub or the search box on docs.python-guide.org

**Comment by jack-yang** [comment]
Ok. Thanks you @sigmavirus24
