### ISSUE TITLE
Revise `consenting adult` verbiage

### ISSUE THREAD

**Issue by taddeimania** [kennethreitz/python-guide#525]
I have been thinking on this suggestion for a while now and I think I may as well put it out there and see how it is received.

I'm proposing we change the verbiage of the popular phrase "We are all consenting adults" to "We are all responsible users".  I don't come by this suggestion lightly so please hear out my reasoning.

### Connotation

First to remove the implicit sexual connotation tied with the phrase.  It may just be popular culture here in the US but if I may explain to those unfamiliar, "Consenting Adults" typically refers to two or more adults who mutually agree to engage in sex.  I have not seen another reference of this nature in the python-guide (admittedly I have not read it completely) and I feel like it is out of place.

### Age Accuracy

For 2 years I have been actively mentoring and surrounding myself with mentors for youth programming camps in my community.  The youngest demographic for these camps is currently the 5th grade and can range up into high school.  Python has a great reputation as a language for youngsters to begin their journey into programming thanks to it's approachable syntax and [welcoming community](https://www.python.org/psf/codeofconduct/).  Removing the 'adult' reference is merely to include those who below our (the US) definition of an adult (age 18).

### Appropriateness 

In my opinion both of the above reasons have merit on their own but when you apply the connotation to the age accuracy the whole phrase seems inappropriate.

### Closing

In closing, I do not take the decision to suggest this edit lightly - I do not even expect it to fall out of popular use among users - but using this document as a beacon for python users both new and seasoned i'd like to see the phrase revised for the above reasons.  Also I do not claim to have the best solution so I happily welcome discourse on the topic.

see: https://github.com/kennethreitz/python-guide/pull/524

Thanks

**Comment by shakefu** [comment]
+1

**Comment by sigmavirus24** [comment]
Fixed by https://github.com/kennethreitz/python-guide/pull/524

**Comment by Asday** [comment]
@sigmavirus24 that's a 404.
