### ISSUE TITLE
% string operator was never deprecated

### ISSUE THREAD

**Issue by memeplex** [kennethreitz/python-guide#543]
Certainly not by PEP 3101. There is some remark in this direction in the What's new document for python 3.0, but it was never really put into practice (just read the str docs for 3.5).

**Comment by sigmavirus24** [comment]
Is this a bug in the guide? Are we claiming that %-formatting is deprecated? Can you link to where? Wouldn't it just be faster to send a pull request to fix this?

**Comment by memeplex** [comment]
In a note at the end of 2.1.7.

**Comment by sigmavirus24** [comment]
@memeplex there is no 2.1.7 reference on http://docs.python-guide.org/en/latest/search/?q=2.1.7&check_keywords=yes&area=default

**Comment by memeplex** [comment]
Ok, I was referring to the pdf, but just search for "became deprecated in Python 3.1" in http://docs.python-guide.org/en/latest/writing/structure/#mutable-and-immutable-types.

**Comment by sigmavirus24** [comment]
@memeplex ah okay. The canonical source is the website. Thanks for the link.
