### ISSUE TITLE
Simplejson wording issue

### ISSUE THREAD

**Issue by ssundarraj** [kennethreitz/python-guide#545]
http://docs.python-guide.org/en/latest/scenarios/json/?highlight=json

Here, it is mentioned that simplejson mimics the behavior of json. But it is my understanding that the simplejson library was made a part of the standard library as json. 

Also, the performance enhancements that simplejson has (due to it's rapid development) have not been mentioned. 

I'm interested in writing about this...

**Comment by sigmavirus24** [comment]
Except simplejson doesn't really have a rapid development model. Just check out [the commits](https://github.com/simplejson/simplejson/commits/master). There are no really significant performance differences between the standard library or simplejson of which I'm aware. If you [read the stdlib source](https://hg.python.org/cpython/file/ca78b9449e04/Lib/json/decoder.py) you'll see imports of `_json` which is a [C module](https://hg.python.org/cpython/file/ca78b9449e04/Modules/_json.c) in the standard library that is compiled for performance on most platforms (if I remember correctly). If you further [read simplejson's setup.py](https://github.com/simplejson/simplejson/blob/master/setup.py#L110..L126) you'll see that if it can't build the C extension on your platform, then it will fallback to a pure Python package (kind of like how the stdlib works).

**Comment by ssundarraj** [comment]
http://stackoverflow.com/questions/712791/what-are-the-differences-between-json-and-simplejson-python-modules

This seems to suggest otherwise doesn't it?

**Comment by sigmavirus24** [comment]
```
 answered Apr 3 '09 at 6:59 
```

**Comment by sigmavirus24** [comment]
Also, look at the next most voted answer (from 2013): http://stackoverflow.com/a/16131316/1953283

**Comment by ssundarraj** [comment]
I didn't spot that. Thanks!
