### ISSUE TITLE
Wheels & Eggs

### ISSUE THREAD

**Issue by heydonovan** [kennethreitz/python-guide#546]
Just discovered [Python Wheels](http://pythonwheels.com/), but don't understand what it does, or why it's better than eggs. Either I'm terrible at using quick search, or it isn't covered in the guide. Thanks, haha!

**Comment by tylerdave** [comment]
I don't see anything in the python-guide but there is some good info in the Python Packaging User Guide:

https://packaging.python.org/en/latest/wheel_egg.html

https://packaging.python.org/en/latest/glossary.html#term-wheel

**Comment by kennethreitz** [comment]
I don't think there's a need for them to be included in the guide at this time, but thanks for the suggestion!
