### ISSUE TITLE
Python2 or Python3

### ISSUE THREAD

**Issue by SanketDG** [kennethreitz/python-guide#550]
What does this guide follow? `py2` or `py3` or somewhere in between? In most of the places, I see that python3 is supported, but in places like reference, there are links to python2 documentation.

**Comment by sigmavirus24** [comment]
If you closely read [this section](http://docs.python-guide.org/en/latest/starting/which-python/) you'll see that @kennethreitz is of the opinion that Python 2.7 is the superior version of Python. That said, the guide attempts to be as objective as possible when possible. Sphinx can only link to one version or the other of standard library documentation so for now we're going to continue using Python 2.
