### ISSUE TITLE
Operator Overloading and Special Methods

### ISSUE THREAD

**Issue by shashvatshukla** [kennethreitz/python-guide#568]
May I start a piece about Operator Overloading in Python and contribute it as a Pull Request.

It'll cover what's here: (https://docs.python.org/3/reference/datamodel.html#special-method-names).
I feel it's a rather handy technique, and a good OOP concept. 

Thanks!

**Comment by sigmavirus24** [comment]
Please explain where you feel it will fit into the guide and how copying content from official documentation will benefit the guide.

**Comment by shashvatshukla** [comment]
I think currently the best section for it would be under code style, recommending its use when implementing a class that has meaningful uses for any of these functions and operators in particular. 

First time programmers may not be aware of this concept and so it being in the official documentation may not benefit them. The guide can contain an introduction to it with a few examples and link to the full list in the documentation.

Thanks!

**Comment by sigmavirus24** [comment]
This has nothing to do with code style and it doesn't fit into any of the existing sections. The guide isn't there to teach you how to write python, it provides resources for people looking to expand their knowledge of Python and pointers to libraries, applications, etc. that will help them in writing Python.

**Comment by shashvatshukla** [comment]
Ah ok. Sorry about that then. Would recommend making that more explicit in the README.

Thanks!
