### ISSUE TITLE
Issue Status Update

### ISSUE THREAD

**Issue by Ribeiro** [kennethreitz/python-guide#587]
I´m trying to contribute to the project somehow, but right now seems a little complicated because issues have already received PR and merged and they remain open. Please, close solved issues asap after merging. Thankx  =)

**Comment by sigmavirus24** [comment]
Could you link to the issues you found that weren't closed?

**Comment by Madrigal** [comment]
I found https://github.com/kennethreitz/python-guide/issues/483 that IMO should have been closed by https://github.com/kennethreitz/python-guide/pull/519, or at least updated to show what's missing
