### ISSUE TITLE
pip install lxml error

### ISSUE THREAD

**Issue by kthotav** [kennethreitz/python-guide#594]
In file included from src/lxml/lxml.etree.c:239:
    /private/var/folders/x5/l9ycnxz16_zczx8nkg_nrfmm0000gn/T/pip-build-Z31ucl/lxml/src/lxml/includes/etree_defs.h:14:10: fatal error: 'libxml/xmlversion.h' file not found
    #include "libxml/xmlversion.h"
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1

**Comment by sigmavirus24** [comment]
This bug report has nothing to do with the python-guide. If you're looking for help installing lxml, please use StackOverflow or `##python` on `irc.freenode.net`.
