### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by tommorris** [kennethreitz/python-guide#646]
The `LICENSE` file in the repository contains Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported (by-nc-sa). The [website](http://docs.python-guide.org/en/latest/) says it is "Creative Commons Share-Alike 3.0" (by-sa) but links to [by-nc-sa](http://creativecommons.org/licenses/by-nc-sa/3.0/).

**Comment by sigmavirus24** [comment]
This is likely a typo. Want to send a PR to fix the typo on the website?

**Comment by TridevGuha** [comment]
need guide about which file to fix

**Comment by tylerdave** [comment]
It looks like this comes from `copyright` in docs/conf.py

**Comment by TridevGuha** [comment]
okay thanks, I sent a PR
