### ISSUE TITLE
Add step to Virtual Environments guide to check if virtualenv is already installed

### ISSUE THREAD

**Issue by brittag** [kennethreitz/python-guide#657]
Along with other Python-related experiments today, I started following the [Virtual Environments guide](http://docs.python-guide.org/en/latest/dev/virtualenvs/), and I wondered why I was getting odd errors after running "pip install virtualenv" (ending with "IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/virtualenv.py'").

After a bit of poking around, I'm guessing I got those errors since virtualenv was actually already installed. It'd be nice to start this guide with brief instructions for checking to see if you already have virtualenv installed, to minimize that kind of confusion. I figure it's not uncommon for newcomers to try various experiments and not keep precise track of what they've done already, or to use setup scripts that install a pile of things and then not be sure what you've installed. :)

**Comment by ueg1990** [comment]
I think you just have to run the command with sudo and it should work.

**Comment by brittag** [comment]
I know that I can override permissions errors with sudo, but when I run a command and get a permissions error that isn't explicitly called out in the documentation as a case where I should run sudo (with an explanation of why), I prefer not to run sudo unless I fully understand the problem and why sudo is the appropriate way to fix it (and in that case, it's usually appropriate to explain that problem and solution in the documentation). :)

**Comment by kikisdeliveryservice** [comment]
A way to check if virtualenv is already installed would be to run virtualenv --version in command line. If a version is returned, it is installed.

**Comment by toanant** [comment]
@brittag created a PR [#811](https://github.com/kennethreitz/python-guide/pull/811)
