### ISSUE TITLE
Note about removal of xrange in Python3

### ISSUE THREAD

**Issue by hckrtst** [kennethreitz/python-guide#665]
docs/writing/style.rst currently has an example of using xrange:
```python
four_lists = [[] for __ in xrange(4)]
```
This does not work for Python3 as xrange functionality is now implemented by range()
as per https://docs.python.org/3/whatsnew/3.0.html

A note can be added to this section to indicate this.

**Comment by kuldeeps48** [comment]
Verified. Submitted a fix.

**Comment by kennethreitz** [comment]
Merged :)
