### ISSUE TITLE
Python 3 installation instructions

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/python-guide#676]

**Comment by kennethreitz** [comment]
maybe

**Comment by Theviajerock** [comment]
Hi... Instructions in all the platforms?

**Comment by adamn** [comment]
I'm setting up Python3 on a new Mac and will submit a Mac update

**Comment by kennethreitz** [comment]
I'm torn about how to present this, honestly. One approach I have in mind is to replicate all the existing installation instructions, with another set for Python 3.

**Comment by adamn** [comment]
It seems like this should be closed in favor of #778

**Comment by Nefari0uss** [comment]
For Linux it might be best to simply state to install using the default package manager and give an example for some of the most common ones:

* Debian/Ubuntu - `apt-get install python3`
* Fedora- `yum install python3`
* Red Hat -  `rpm install python3`
* Arch Linux - `pacman -S python3`

Please correct me if I'm wrong on yum/rpm. I only know the syntax for apt and pacman and model what I thought it might be based on the [Wikipedia](https://en.wikipedia.org/wiki/Package_manager) page.

**Comment by userlerueda** [comment]
@kennethreitz @adamn  should we close this one and work on #778 ?

**Comment by kennethreitz** [comment]
Closed for #778
