### ISSUE TITLE
Error on the Context Managers section ?

### ISSUE THREAD

**Issue by ewjoachim** [kennethreitz/python-guide#686]
So what's said [here](http://docs.python-guide.org/en/latest/writing/structure/#context-managers) is :

```python
from contextlib import contextmanager

@contextmanager
def custom_open(filename):
    f = open(filename)
    yield f
    f.close()

with custom_open('file') as f:
    contents = f.read()
```

But as far as I undestand, we shoud wrap the ``yield`` into a ``try:`` block with the ``close`` in the ``finally:``, otherwise a exception might allow leaving the ``with`` block without calling ``close``. I might do a PR for this, but I wanted to check with someone if there was a reason the code was shown this way and/or if I was mistaken altogether...

**Comment by kennethreitz** [comment]
Without looking too much into this, it sounds like a good improvement.
