### ISSUE TITLE
Web frameworks section misrepresents Pyramid.

### ISSUE THREAD

**Issue by cguardia** [kennethreitz/python-guide#693]
Hi,

On this page:

https://github.com/kennethreitz/python-guide/blob/master/docs/scenarios/web.rst

You say Pyramid is "a lot like Django", which is not correct. Better wording for that would be something like:

"Pyramid is a very flexible framework with a heavy focus on modularity. It comes with a small number of libraries ("batteries") built-in, and encourages users to extend its base functionality."

FWIW, given your preference for Django/Flask over anything else, you could probably remove mentions of other frameworks, because rather than being inclusive, it feels like they are singled out for exclusion.

Thanks.

**Comment by kennethreitz** [comment]
If you send a PR with that change to the Pyramid paragraph, I'll merge it.

**Comment by toanant** [comment]
@kennethreitz   this Issue can be closed now.

**Comment by cguardia** [comment]
Thanks!
