### ISSUE TITLE
Please write about Numba, threading and multiprocessing (Speed section)

### ISSUE THREAD

**Issue by andportnoy** [kennethreitz/python-guide#700]

**Comment by Michael-F-Bryan** [comment]
It might be good to mention the [concurrent.futures][concurrent] module under threading and multiprocessing. Both the [ThreadPoolExecutor][tpe] and [ProcessPoolExecutor][ppe] classes make concurrency incredibly easy, compared with using  the underlying threading and multiprocess modules manually.

[concurrent]: https://docs.python.org/3/library/concurrent.futures.html
[tpe]: https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor
[ppe]: https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor

**Comment by Puranjay25** [comment]
Is this issue resolved?
