### ISSUE TITLE
Library vs Application

### ISSUE THREAD

**Issue by guettli** [kennethreitz/python-guide#703]
I stumbled over the words "Library" and "Application" in the logging guide:
http://docs.python-guide.org/en/latest/writing/logging/

I think that this distinction is very important and not clear to many programmers.

Unfortunately the django framework defines the term "app" different:

 https://docs.djangoproject.com/en/1.9/ref/applications/#projects-and-applications

AFAIK the basic problem is this: Exactly one python package can be special (like providing a sitecustomize.py). But AFAIK there is no common name for it in the python community.

What can be done now?

I see two choices:

1. Define the terms yourself/ourself in the python-guide

2. Relaxed Escalate: Ask the python core developers for a definition.

**Comment by drpoggi** [comment]
> Relaxed Escalate: Ask the python core developers for a definition.

At least one core developer has written about this: https://caremad.io/2013/07/setup-vs-requirement/

Donald's definitions makes sense to me. Django's naming confuses things, but the implementation of apps(that I've come across) pretty closely follows his "library" definition. I agree that a section outlining this distinction would be useful, as the guide does advertise itself as accessible to novices, where the difference can be unclear.

**Comment by guettli** [comment]
I asked on python-ideas: https://mail.python.org/pipermail/python-ideas/2016-May/040287.html

**Comment by guettli** [comment]
Just for the records, I am missing a term for the thing which provides the environment.

I created an issue here: https://github.com/pypa/python-packaging-user-guide/issues/236

It would be nice if you could help to find a common name.

**Comment by guettli** [comment]
It seems that nobody is missing a term for this. Neither here nor on python-ideas. Closing this.
