### ISSUE TITLE
Question about translation

### ISSUE THREAD

**Issue by jihobak** [kennethreitz/python-guide#719]
Hello, I'm jiho Bak.
I would like to say thanks  for your amazing book.

I noticed someone try to make korean version. 
I would like to translate this book to korean ,studying python.

Where should I check contact?

Thanks

**Comment by kennethreitz** [comment]
- fork the repo on github
- start translating
- host it on readthedocs
- i'll add a link in the sidebar!

**Comment by jihobak** [comment]
@kennethreitz  Thanks!!
