### ISSUE TITLE
Add link to full French translation

### ISSUE THREAD

**Issue by ThomasG77** [kennethreitz/python-guide#730]
As stated in a previous comment in one of my PR https://github.com/kennethreitz/python-guide/pull/729#issuecomment-233150779 , you will find the French translation at http://python-guide-fr.readthedocs.io
Can you add the link?
Do you need any action on my side?

**Comment by kennethreitz** [comment]
A PR would be easiest, but I can add it :)

**Comment by kennethreitz** [comment]
This is now live! Thanks so much for doing this :)

:sparkles: :cake: :sparkles:

**Comment by ThomasG77** [comment]
Thanks to your original content and the numerous contributors additions. Without, this translation would have not been possible!
