### ISSUE TITLE
Web Applications:Frameworks advice too vague to be useful

### ISSUE THREAD

**Issue by vassudanagunta** [kennethreitz/python-guide#731]
On Flask vs Django:

> Flask is a “microframework” for Python, and is an excellent choice for building smaller applications, APIs, and web services.

What is the threshold between "smaller" and larger applications? 

> Flask is default choice for any Python web application that isn’t a good fit for Django.

What makes an app not "a good fit for Django"? 

If you already know the answers to these questions, you wouldn't need to be reading this advice! In other words, it isn't very helpful to the very people reading it. 

If I knew the answer I'd submit a pull request, but sadly I don't. What is needed are minimally ambiguous criteria for when to use one versus the other, with some backing explanation in-line or in footnotes. For example, this [Django vs Flask Worksheet](https://wakatime.com/django-vs-flask-worksheet) uses eight criteria. I don't know if they are the right ones but I provide the reference as an example.

**Comment by kennethreitz** [comment]
Thank you for your feedback. It will be put into consideration.
