### ISSUE TITLE
sklearn guide

### ISSUE THREAD

**Issue by shivenmian** [kennethreitz/python-guide#755]
@kennethreitz Would it be good if I wrote up a small intro to [sklearn](http://scikit-learn.org/)? There's no section in the guide about the widely-used machine learning packages python has (apart from NumPy and SciPy, which are actually helper packages in ML), so is that something you'd like to have?

**Comment by kennethreitz** [comment]
sure!

**Comment by PaulReiber** [comment]
@shivenmian If you'd like someone to help via edit/review passes of the content I'd be happy to assist.  Don't hesitate to reach out.

**Comment by shivenmian** [comment]
Sure, if I need any help I'll ask :)

**Comment by shivenmian** [comment]
Fixed in #760
