### ISSUE TITLE
Missing link for "ez_setup.py"

### ISSUE THREAD

**Issue by pitalig** [kennethreitz/python-guide#766]
At the page "python-guide/docs/starting/install/win.rst", the link "https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py" get a 404 page on bitbucket.
I found this another link in Python Package Index: "https://bootstrap.pypa.io/ez_setup.py", if someone can confirm this is the correct link, I can create a pull-request to change.

**Comment by kennethreitz** [comment]
Thanks! Would you mind sending a pull request?

**Comment by pituca292** [comment]
@kennethreitz No problem, I will send it! 
Just to check, do I know if this link is mentioned anywhere else? I searched, but only found this occurrence. So, if there are any other appearences, I can update they all.

**Comment by pituca292** [comment]
#767 
Pull request sent! :)

**Comment by userlerueda** [comment]
@pitalig since this has been merged using PR can you close this issue ? In the future you can do this automatically by placing `closes #766` in the details of the PR.
