### ISSUE TITLE
Please stop putting people off Python 3

### ISSUE THREAD

**Issue by obestwalter** [kennethreitz/python-guide#770]
First things first: @kennethreitz  you are one of my heroes in the Python world. Period. You gave us some really great tools and you provided orientation. If I ever meet you IRL I will bow down before you and ... [you know](https://www.youtube.com/watch?v=-FucbvoFFy0). 

This guide that you started has also quite a weight (a.k.a. link juice). If you google for "Python guide" guess what you find ... so I am pretty sure that this guide has a great influence over what choices newcomers to the Python world make. This is why I am concerned about the Python2 vs Python3 page. 

I really think that in 2016 there should be no discussion anymore about which version of Python should be used if you are a newcomer or if you start a new project. I agree that there is a lot of legacy code that is still Python2 (but most of it is behind corporate walls). I feel their pain but Python3 is the present and future of the language and we as a community should really stand behind this.

So in my VeryHumbleOpinion(TM) [this page](http://docs.python-guide.org/en/latest/starting/which-python/#the-state-of-python-2-vs-3) needs to be rewritten drastically to basically say: 

If you learn Python or start a new project: use Python 3 (because it's really great and actively developed).

Only use Python2 if you are forced at gun point ... e.g you have to work with a Python2 legacy code base.

If everybody agrees I am happy to update it and send a PR.

**Comment by kennethreitz** [comment]
lol thanks for the kind words!

I do plan to revisit the python 2 vs 3 page very soon. It's still appropriate, I'd say, but needs some TLC towards the effect of "you should be using 3 unless you have a reason not to".

**Comment by kennethreitz** [comment]
updated

**Comment by kennethreitz** [comment]
ok i think it's better now. what do you think?

**Comment by kennethreitz** [comment]
made quite a few changes

**Comment by obestwalter** [comment]
@kennethreitz thanks a lot - I think this is much more reflecting the current situation that nobody has to be scared to pick up Python3 anymore :)
