### ISSUE TITLE
Missing space in the IDE section

### ISSUE THREAD

**Issue by willhumphreys** [kennethreitz/python-guide#772]
In the IDE section for PyCharm and IntelliJ IDEA there is a spacing missing after 'Community Edition' and before the open bracket.

http://docs.python-guide.org/en/latest/dev/env/#ides

> Professional Edition (Free 30-day trial) and Community Edition(Apache 2.0 License) with fewer features.

**Comment by kennethreitz** [comment]
✨🍰✨
