### ISSUE TITLE
Suggestion for http://docs.python-guide.org/en/latest/scenarios/scrape/#lxml-and-requests

### ISSUE THREAD

**Issue by redstoneleo** [kennethreitz/python-guide#784]
In this part http://docs.python-guide.org/en/latest/scenarios/scrape/#lxml-and-requests
there is no need to use requests.get to retrieve the web page, lxml has the convenient function 
http://lxml.de/api/lxml.html-pysrc.html#parse
```
>>> from lxml.html import parse
>>> parse('http://www.crifan.com/python_try_lxml_parse_html/')
<lxml.etree._ElementTree object at 0x021C2AD0>
>>> 
```

**Comment by kennethreitz** [comment]
I think using requests here is a better example.
