### ISSUE TITLE
Add translation to Brazilian Portuguese

### ISSUE THREAD

**Issue by rgiovanini** [kennethreitz/python-guide#788]
As the title says, I would like to help to translate this guide to PT-BR. But I don't know how to setup the repository and other things...

**Comment by kennethreitz** [comment]
just fork it and set it up on read the docs, the send me the link!

**Comment by rgiovanini** [comment]
Ok, kenneth. I'll start working. Thanks!

**Comment by vcaldas** [comment]
@rgiovanini I was thinking tb on that too!  I'm what stage are you?

**Comment by vcaldas** [comment]
Hi @rgiovanini  and @kennethreitz . I just set up the repository and the Readthedocs.
[https://readthedocs.org/projects/python-guide-pt-br/]
I'm just getting my hands on the translation. Cheers.  👍

**Comment by vcaldas** [comment]
@rgiovanini You can fork the Pt-br working files to help on the trasnlation
https://github.com/vcaldas/python-guide-pt_br

**Comment by rgiovanini** [comment]
Nice, @vcaldas! I'll fork it and start working. Abração!

**Comment by vcaldas** [comment]
@rgiovanini  I'm still having issues on the translation. For some reason it does not appear online. But locally Works. @kennethreitz Any idea why?

**Comment by vcaldas** [comment]
Translation environment set:
Please visit:
https://www.transifex.com/own-16/python-guide-pt_br/
