### ISSUE TITLE
Virtualenvs documentation does not produce a clear virtual environment

### ISSUE THREAD

**Issue by userlerueda** [kennethreitz/python-guide#795]
In my opinion [virtualenvs](https://github.com/kennethreitz/python-guide/blob/master/docs/dev/virtualenvs.rst) documentation should be changed, instead of creating a virtual environment named venv, should we be creating a virtual environment with a more explicit name ? something like my_project, if you have multiple projects and ( venv ) appears to the left of the prompt, it will not really tell you much about which environment you are using.

**Comment by kennethreitz** [comment]
pull requests accepted!
