### ISSUE TITLE
Link from "Structure / Tests" to "Testing Your Code"

### ISSUE THREAD

**Issue by guettli** [kennethreitz/python-guide#806]
It would be nice to have a link from

 http://docs.python-guide.org/en/latest/writing/structure/#test-suite

to

 http://docs.python-guide.org/en/latest/writing/tests/

This would make the learning-flow easier. At least for people reading the online version.

**Comment by oscles** [comment]
how can i to help???

**Comment by guettli** [comment]
@oscles you could provide a pull request. I don't have commit privileges, but I guess providing more internal hyperlinks will get accepted.
