### ISSUE TITLE
Missing validation at Common Gotchas

### ISSUE THREAD

**Issue by monchitos82** [kennethreitz/python-guide#813]
A missing validation in the example provided at [Common Gotchas](http://python-guide-pt-br.readthedocs.io/en/latest/writing/gotchas/) can lead to unexperienced people using it wrongly (_those copy-paste guys_).
I know it breaks the context but it can be a misleading example.

What about using:
```python
def append_to(element, to=None):
    if to is None:
        to = []
    elif isinstance(to, list):
        to.append(element)
    else:
        print('Invalid argument')
    return to
```
Or even better, just saying that this will only work when we pass a **list**

**Comment by kennethreitz** [comment]
please send a pull request!
