### ISSUE TITLE
Are there naming conventions for pip requirements files?

### ISSUE THREAD

**Issue by kwill** [kennethreitz/python-guide#821]
I need to store multiple pip requirements files. For example, one file for simply running the program, another for day-to-day development, another for making a Windows build.

There is no mention of storing multiple requirements files in [Structuring your project](https://python-guide.readthedocs.io/en/latest/writing/structure/#requirements-file) or the [pip install](https://pip.pypa.io/en/stable/reference/pip_install/) documentation.

Also asked here https://stackoverflow.com/questions/44264013 (mentions some conventions I've seen in the wild).

**Comment by daegontaven** [comment]
Adding multiple requirement files is one way to do things. A neater way is to add the details to a setup.cfg file. Then install using pip. So `pip install .[DEV]` for the development requirements and `pip install .[DOCS]` for documentation. I'm writing the documentation for it. Hopefully it gets merged when I pull.

**Comment by kennethreitz** [comment]
I highly recommend only having one file :)

**Comment by kennethreitz** [comment]
But I understand that's impossible sometimes.

**Comment by kennethreitz** [comment]
`requirements-win.txt`.

**Comment by kwill** [comment]
Looks like this might be solved in part by [requirement-specifiers](https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers) (although there are other annoying reasons I end up splitting requirements).
