### ISSUE TITLE
Blueprint TODO still relevant for python-guide/docs/scenarios/admin.rst ?

### ISSUE THREAD

**Issue by bobsawey** [kennethreitz/python-guide#827]
Noticed 
> TODO:  write about blueprint 

Located in python-guide/docs/scenarios/admin.rst 

I might have missed it, but didn't see an issue related. Was wondering if a low priority task needs to be created to either remove that section or to complete writing of the section.

Hope this helps. Cheers -B

**Comment by kennethreitz** [comment]
up to you :)
