### ISSUE TITLE
Why should underscores be avoided in module names?

### ISSUE THREAD

**Issue by elanorigby** [kennethreitz/python-guide#828]
"If you’d like you could name your module my_spam.py, but even our friend the underscore should not be seen often in module names."
- https://python-guide-pt-br.readthedocs.io/en/latest/writing/structure/#modules

I actually thought it was convention to separate words with underscores in file/module names. Why is it a bad idea?

**Comment by Zopieux** [comment]
You *have* to use underscores to separate module name words as other characters (spaces or hyphens) will prevent importing (`-` is the subtract operator).

What I think the author actually meant is that you should try *not to use* multiple words. Keep the names short. And, most of all, don't namespace with underscores, use sub modules instead.

```python
# OK
import library.plugin.foo
# not OK
import library.foo_plugin
```
