### ISSUE TITLE
BTC Link overlaps text in the body

### ISSUE THREAD

**Issue by biggert** [kennethreitz/python-guide#836]
This [commit](https://github.com/kennethreitz/python-guide/commit/6656c15227014a5bfce1f9cacd2a3b6673fcb373) introduced a link whose anchor text is so long that it overlaps the text in the body of the page(s). I've included 2 examples showing the overlap in my browser (Chrome 60, OS X).

![http://i.imgur.com/6SKVN7t.png](http://i.imgur.com/6SKVN7t.png)

---

![http://i.imgur.com/rs3CCCV.png](http://i.imgur.com/rs3CCCV.png)

**Comment by kennethreitz** [comment]
Ew. Thanks for the report!

Strange, because [Requests](https://docs.python-requests.org/) uses the same text and theme and it automatically wraps.

**Comment by kennethreitz** [comment]
fixed.
