### ISSUE TITLE
add Falcon to web frameworks

### ISSUE THREAD

**Issue by ofek** [kennethreitz/python-guide#839]
@kennethreitz https://github.com/falconry/falcon was created at Rackspace by @kgriffs

Currently, the guide lacks mention of a framework specifically for APIs. This is a more important topic than ever before with the rise of the cloud and shift towards mobile and SPAs.

**Comment by anlewis** [comment]
Hi there! I’m hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!
