### ISSUE TITLE
Filipino Translation/Localization

### ISSUE THREAD

**Issue by themarshann** [kennethreitz/python-guide#879]
Hello!
I'd like to contribute by translating this document into the Filipino language so that it will reach a wider audience, may I?
Thank you.

**Comment by kennethreitz** [comment]
sure!

**Comment by themarshann** [comment]
I've already forked the repo and renamed it `python-guide-fil`. I just wanna ask though...after working on the translations, what are the next steps I should do?

Thanks in advance.

**Comment by kennethreitz** [comment]
publish it to readthedocs.org, and then send a PR with a link to your translation in the sidebar!

**Comment by themarshann** [comment]
http://python-guide-fil.readthedocs.io/en/latest/?

I've only managed to translate a bit, but this is how it looks like so far. Hope I'm doing the right thing though.

**Comment by kennethreitz** [comment]
beautiful!

**Comment by kennethreitz** [comment]
https://github.com/kennethreitz/python-guide/commit/88003441dde9d6ff4134fe3475e8a391a4697ebb

**Comment by kennethreitz** [comment]
live! http://docs.python-guide.org/en/latest/

**Comment by themarshann** [comment]
Great! Will do the other parts little by little. Thanks :)
